"""
export_realizations.py — Expand realizations.nc to N synthetic realizations
                          and write them as .npy and Zarr on disk.

Starting from the source NetCDF (which may contain fewer realizations than the
target), additional realizations are generated by cycling through the source
data and adding per-realization Gaussian noise to all non-NaN pixels.  This
produces a realistic ensemble spread suitable for benchmarking compression
ratios, chunking strategies, and partial-update performance.

Outputs
-------
  <out>/realizations.npy    — NumPy binary, shape (N, y, x), float32
  <out>/realizations.zarr/  — Zarr v3 group:
                                  realizations  (N, y, x)  float32, compressed
                                  i, y, x       coordinate arrays

Usage
-----
  python export_realizations.py
  python export_realizations.py --nc ./data/realizations.nc --out ./data
  python export_realizations.py --n-realizations 100 --noise-sigma 15.0

Arguments
---------
  --nc               Source NetCDF file (default: ./data/realizations.nc)
  --out              Output directory   (default: same directory as --nc)
  --n-realizations   Number of output realizations to generate (default: 100)
  --noise-sigma      Std dev of the Gaussian noise added to each realization,
                     in the same units as the data (default: 10.0)
  --seed             Random seed for reproducibility (default: 42)
"""

import argparse
import time
from pathlib import Path

import netCDF4 as nc
import numpy as np
import zarr
from zarr.codecs import BloscCodec


def log(msg: str) -> None:
    print(msg, flush=True)


def export(
    nc_path: Path,
    out_dir: Path,
    n_output: int,
    noise_sigma: float,
    seed: int,
) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    rng = np.random.default_rng(seed)

    # ── Open source ───────────────────────────────────────────────────────────
    log(f"Opening {nc_path} …")
    src     = nc.Dataset(nc_path, "r")
    src_var = src.variables["__xarray_dataarray_variable__"]
    n_src, ny, nx = src_var.shape
    log(
        f"Source : {n_src} realizations, grid {ny} × {nx},  dtype {src_var.dtype}\n"
        f"Output : {n_output} realizations,  noise σ = {noise_sigma}"
    )

    # Read all source slices up front — they're small (3 × y × x) and reused
    log("Loading source realizations …")
    src_data = np.ma.filled(src_var[:].astype("float32"), fill_value=np.nan)
    # (n_src, ny, nx) — plain float32, NaN where masked

    # ── Prepare outputs ───────────────────────────────────────────────────────
    npy_path  = out_dir / "realizations.npy"
    zarr_path = out_dir / "realizations.zarr"

    # .npy — create the file with the correct header, then fill via memmap
    npy_out = np.lib.format.open_memmap(
        npy_path, mode="w+", dtype="float32", shape=(n_output, ny, nx)
    )

    # Zarr — create group and pre-allocate the realizations array
    zgroup = zarr.open_group(str(zarr_path), mode="w")
    zarr_arr = zgroup.create_array(
        "realizations",
        shape=(n_output, ny, nx),
        chunks=(1, 128, 128),       # one realization per chunk slab for streaming writes
        dtype="float32",
        compressors=BloscCodec(cname="zstd", clevel=5),
        dimension_names=["i", "y", "x"],
        overwrite=True,
    )

    # ── Write one realization at a time ───────────────────────────────────────
    log(f"Generating {n_output} realizations …")
    t0 = time.perf_counter()

    for i in range(n_output):
        base  = src_data[i % n_src].copy()           # (ny, nx)
        valid = ~np.isnan(base)
        noise = rng.normal(0.0, noise_sigma, size=(ny, nx)).astype("float32")
        base[valid] += noise[valid]                  # noise only on valid pixels

        npy_out[i]   = base
        zarr_arr[i]  = base

        if (i + 1) % 10 == 0 or i == n_output - 1:
            elapsed = time.perf_counter() - t0
            log(f"  {i + 1:3d}/{n_output}  ({elapsed:.1f}s)")

    # Flush the memmap to disk
    npy_out.flush()
    del npy_out

    # ── Write coordinates ─────────────────────────────────────────────────────
    i_vals = np.arange(n_output, dtype="int64")
    y_vals = src.variables["y"][:].astype("float32")
    x_vals = src.variables["x"][:].astype("float32")

    for coord_name, vals in [("i", i_vals), ("y", y_vals), ("x", x_vals)]:
        zgroup.create_array(
            coord_name,
            shape=vals.shape,
            dtype=vals.dtype,
            chunks=vals.shape,
            dimension_names=[coord_name],
            overwrite=True,
        )
        zgroup[coord_name][:] = vals

    src.close()

    elapsed = time.perf_counter() - t0
    log(
        f"\nDone in {elapsed:.1f}s\n"
        f"  NumPy : {npy_path}  ({npy_path.stat().st_size / 1e9:.2f} GB)\n"
        f"  Zarr  : {zarr_path}"
    )


def main() -> None:
    p = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument(
        "--nc", default="./data/realizations.nc",
        help="Source NetCDF file (default: ./data/realizations.nc)",
    )
    p.add_argument(
        "--out", default=None,
        help="Output directory (default: same directory as --nc)",
    )
    p.add_argument(
        "--n-realizations", type=int, default=100,
        help="Number of output realizations to generate (default: 100)",
    )
    p.add_argument(
        "--noise-sigma", type=float, default=10.0,
        help="Gaussian noise std dev in data units (default: 10.0)",
    )
    p.add_argument(
        "--seed", type=int, default=42,
        help="Random seed for reproducibility (default: 42)",
    )
    args = p.parse_args()

    nc_path = Path(args.nc)
    out_dir = Path(args.out) if args.out else nc_path.parent

    if not nc_path.exists():
        p.error(f"NetCDF file not found: {nc_path}")

    export(nc_path, out_dir, args.n_realizations, args.noise_sigma, args.seed)


if __name__ == "__main__":
    main()
